version: '3.8'

services:
  superchart-backend:
    image: ghcr.io/stone-w4tch3r/superchart-backend:release
    ports:
      - "5001:8080"
    environment:
      - SWAGGER_BASIC_AUTH_USERNAME
      - SWAGGER_BASIC_AUTH_PASSWORD
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
