name: Deploy backend to Render

on:
  workflow_run:
    workflows: [ "Publish backend Docker image" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@v1.7.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false